import type {
  AuthEvent as PiAuthEvent,
  AuthInteraction as PiAuthInteraction,
  AuthPrompt as PiAuthPrompt,
  CredentialStore,
  LoginOptions,
  Models,
  MutableModels,
  Provider,
} from "@earendil-works/pi-ai";
import { AdapterError } from "../../core/adapter-error";
import { filterModelsByCapabilities } from "../../core/filter-models";
import { normalizeModels, normalizeProviders } from "../../core/normalize-catalog";
import { redactSensitiveText } from "../../core/redact-sensitive";
import { validateCustomEndpoint, validateModelId } from "../../core/validate-custom-endpoint";
import { abortError, throwIfAborted, withAbort, safeAdapterError } from "./operation";
import type {
  AuthEvent,
  AuthPrompt,
  AuthStatus,
  ConnectOptions,
  ConnectionRequest,
  ModelSelection,
  ModelSettingsAdapter,
  ModelSummary,
  ProviderSummary,
} from "../../core/types";
import { createOpenAICompatibleProvider } from "./openai-compatible";

export { createOpenAICompatibleProvider } from "./openai-compatible";
export type { CustomModelSelection } from "./openai-compatible";

export type PiAiModels = Pick<
  Models,
  | "getProviders"
  | "getProvider"
  | "getModels"
  | "getModel"
  | "checkAuth"
  | "login"
  | "logout"
  | "completeSimple"
> &
  Partial<Pick<Models, "refresh" | "getAuth">> &
  Partial<Pick<MutableModels, "setProvider">>;

export interface PiAiRefreshOptions {
  providerIds?: readonly string[];
  force?: boolean;
  allowNetwork?: boolean;
  signal?: AbortSignal;
}

export interface PiAiRefreshResult {
  errors: ReadonlyMap<string, AdapterError>;
}

export interface PiAiAdapter extends ModelSettingsAdapter {
  refresh(options?: PiAiRefreshOptions): Promise<PiAiRefreshResult>;
  /** Resolves request-time auth (including OAuth refresh) but returns only non-secret status. */
  resolveAuthStatus(providerId: string, signal?: AbortSignal): Promise<AuthStatus>;
}

export interface PiAiAdapterOptions {
  models: PiAiModels;
  /** Must be the same store that was passed to createModels(). */
  credentials: CredentialStore;
  probePrompt?: string;
  probeTimeoutMs?: number;
  /** Providers whose standard API key may be written directly when Pi AI has no login flow. */
  apiKeyFallbackProviderIds?: readonly string[];
  /** Stable host installation ID needed by some OAuth flows; not generated by the component. */
  loginOptions?: LoginOptions;
}

function mapProvider(provider: Provider, apiKeyFallbackProviders: ReadonlySet<string>): ProviderSummary {
  const apiKey = provider.auth.apiKey;
  const oauth = provider.auth.oauth;
  return {
    id: provider.id,
    name: provider.name,
    auth: {
      ...(oauth?.login
        ? {
            oauth: {
              label: oauth.loginLabel ?? oauth.name,
              isSubscription: oauth.isSubscription ?? false,
            },
          }
        : {}),
      ...(apiKey
        ? {
            apiKey: {
              label: apiKey.name,
              interactive: Boolean(apiKey.login) || apiKeyFallbackProviders.has(provider.id),
            },
          }
        : {}),
      ...(apiKey && !apiKey.login && !apiKeyFallbackProviders.has(provider.id)
        ? { ambient: true }
        : {}),
    },
  };
}

function mapModel(model: ReturnType<Models["getModels"]>[number]): ModelSummary {
  return {
    id: model.id,
    providerId: model.provider,
    name: model.name,
    input: [...model.input],
    reasoning: model.reasoning,
    contextWindow: model.contextWindow,
    maxTokens: model.maxTokens,
    cost: {
      input: model.cost.input,
      output: model.cost.output,
      cacheRead: model.cost.cacheRead,
      cacheWrite: model.cost.cacheWrite,
    },
  };
}

function mapPrompt(prompt: PiAuthPrompt): AuthPrompt {
  if (prompt.type === "select") {
    return {
      type: "select",
      message: prompt.message,
      options: prompt.options,
      signal: prompt.signal,
    };
  }
  return {
    type: prompt.type === "manual_code" ? "manual-code" : prompt.type,
    message: prompt.message,
    placeholder: prompt.placeholder,
    signal: prompt.signal,
  };
}

function mapEvent(event: PiAuthEvent): AuthEvent {
  switch (event.type) {
    case "auth_url":
      return { type: "auth-url", url: event.url, instructions: event.instructions };
    case "device_code":
      return {
        type: "device-code",
        userCode: event.userCode,
        verificationUri: event.verificationUri,
        expiresInSeconds: event.expiresInSeconds,
      };
    default:
      return { type: event.type, message: event.message };
  }
}

function interaction(options: ConnectOptions, secrets: string[]): PiAuthInteraction {
  const clean = (value: string) => redactSensitiveText(value, secrets);
  return {
    signal: options.signal,
    notify: (event) => {
      if (options.signal?.aborted) return;
      const mapped = mapEvent(event);
      options.onEvent?.(mapped.type === "auth-url"
        ? { ...mapped, url: clean(mapped.url), instructions: mapped.instructions ? clean(mapped.instructions) : undefined }
        : mapped.type === "device-code"
          ? { ...mapped, verificationUri: clean(mapped.verificationUri) }
          : { ...mapped, message: clean(mapped.message) });
    },
    prompt: async (prompt) => {
      if (!options.prompt) {
        throw new AdapterError("capability", "此认证流程需要宿主提供 prompt handler");
      }
      const signal = prompt.signal && options.signal ? AbortSignal.any([prompt.signal, options.signal]) : prompt.signal ?? options.signal;
      const mapped = mapPrompt(prompt);
      const safePrompt: AuthPrompt = mapped.type === "select"
        ? { ...mapped, message: clean(mapped.message), options: mapped.options.map((option) => ({ ...option, label: clean(option.label), description: option.description ? clean(option.description) : undefined })), signal }
        : { ...mapped, message: clean(mapped.message), placeholder: mapped.placeholder ? clean(mapped.placeholder) : undefined, signal };
      const answer = await withAbort(() => options.prompt!(safePrompt), signal);
      if (prompt.type === "secret" || prompt.type === "manual_code") secrets.push(answer);
      return answer;
    },
  };
}

function customSelectionFromRequest(
  request: Extract<ConnectionRequest, { connectionType: "custom" }>,
): Extract<ModelSelection, { connectionType: "custom" }> {
  return {
    connectionType: "custom",
    authMethod: request.authMethod,
    providerId: request.providerId,
    modelId: request.modelId,
    custom: request.custom,
  };
}

export function createPiAiAdapter(options: PiAiAdapterOptions): PiAiAdapter {
  const probePrompt = options.probePrompt ?? "Respond with OK.";
  const probeTimeoutMs = options.probeTimeoutMs ?? 15_000;
  if (!Number.isFinite(probeTimeoutMs) || probeTimeoutMs <= 0 || probeTimeoutMs > 2_147_483_647) throw new AdapterError("validation", "探测超时必须为有效的正毫秒数");
  const apiKeyFallbackProviders = new Set(options.apiKeyFallbackProviderIds ?? ["openai", "anthropic", "google", "openrouter"]);
  const customSelections = new Map<string, Extract<ModelSelection, { connectionType: "custom" }>>();

  function registerCustom(selection: Extract<ModelSelection, { connectionType: "custom" }>) {
    if (!options.models.setProvider) throw new AdapterError("capability", "Models 实例不支持注册自定义 provider");
    const safeSelection: Extract<ModelSelection, { connectionType: "custom" }> = {
      connectionType: "custom", providerId: selection.providerId, authMethod: selection.authMethod,
      modelId: validateModelId(selection.modelId), custom: validateCustomEndpoint(selection.custom),
    };
    options.models.setProvider(createOpenAICompatibleProvider(safeSelection));
    customSelections.set(selection.providerId, safeSelection);
  }

  async function statusMethod(providerId: string, type: "api_key" | "oauth", signal?: AbortSignal): Promise<AuthStatus["method"]> {
    if (customSelections.get(providerId)?.authMethod === "none") return "none";
    if (type === "oauth") return "oauth";
    const stored = await withAbort(() => options.credentials.list({ signal }), signal);
    return stored.some((entry) => entry.providerId === providerId && entry.type === "api_key") ? "api-key" : "ambient";
  }

  async function saveApiKey(providerId: string, key: string, signal: AbortSignal) {
    await withAbort(() => options.credentials.modify(
      providerId,
      async () => {
        throwIfAborted(signal);
        return { type: "api_key", key };
      },
      { signal },
    ), signal);
  }

  async function refresh(operation: PiAiRefreshOptions = {}): Promise<PiAiRefreshResult> {
    throwIfAborted(operation.signal);
    if (!options.models.refresh) throw new AdapterError("capability", "Models 实例不支持动态目录刷新");
    try {
      const result = await withAbort(() => options.models.refresh!({ providers: operation.providerIds, force: operation.force, allowNetwork: operation.allowNetwork ?? true, signal: operation.signal }), operation.signal);
      if (result.aborted) throw abortError();
      const errors = new Map<string, AdapterError>();
      for (const [providerId, cause] of result.errors) errors.set(providerId, safeAdapterError(cause, "catalog"));
      return { errors };
    } catch (cause) {
      if (operation.signal?.aborted || (cause instanceof DOMException && cause.name === "AbortError")) throw abortError();
      throw safeAdapterError(cause, "catalog");
    }
  }

  async function getAuthStatus(providerId: string, signal?: AbortSignal): Promise<AuthStatus> {
    try {
      throwIfAborted(signal);
      const result = await withAbort(() => options.models.checkAuth(providerId, { signal }), signal);
      throwIfAborted(signal);
      return result
        ? {
            state: "configured",
            method: await statusMethod(providerId, result.type, signal),
            source: result.source ? redactSensitiveText(result.source) : undefined,
          }
        : { state: "unconfigured" };
    } catch (cause) {
      if (signal?.aborted || (cause instanceof DOMException && cause.name === "AbortError")) throw abortError();
      return {
        state: "error",
        message: safeAdapterError(cause, "auth").message,
      };
    }
  }

  async function resolveAuthStatus(providerId: string, signal?: AbortSignal): Promise<AuthStatus> {
    throwIfAborted(signal);
    if (!options.models.getAuth) throw new AdapterError("capability", "Models 实例不支持请求凭证解析");
    try {
      const checked = await withAbort(() => options.models.checkAuth(providerId, { signal }), signal);
      if (!checked) return { state: "unconfigured" };
      const resolved = await withAbort(() => options.models.getAuth!(providerId, { signal }), signal);
      if (!resolved) return { state: "unconfigured" };
      const secrets = [resolved.auth.apiKey ?? "", ...Object.values(resolved.auth.headers ?? {}).filter((value): value is string => typeof value === "string")];
      return { state: "configured", method: await statusMethod(providerId, checked.type, signal), source: resolved.source ? redactSensitiveText(resolved.source, secrets) : undefined };
    } catch (cause) {
      if (signal?.aborted || (cause instanceof DOMException && cause.name === "AbortError")) throw abortError();
      return { state: "error", message: safeAdapterError(cause, "auth").message };
    }
  }

  return {
    async listProviders(operation = {}) {
      throwIfAborted(operation.signal);
      try {
        return normalizeProviders(options.models.getProviders().map((provider) => mapProvider(provider, apiKeyFallbackProviders)));
      } catch (cause) { throw safeAdapterError(cause, "catalog"); }
    },

    async listModels(operation) {
      throwIfAborted(operation.signal);
      try {
        const provider = options.models.getProvider(operation.providerId);
        if (!provider) throw new AdapterError("catalog", "找不到指定的 provider");
        if (provider.refreshModels) {
          const result = await refresh({ providerIds: [operation.providerId], force: operation.refresh, signal: operation.signal });
          const failure = result.errors.get(operation.providerId);
          if (failure) throw failure;
        }
        throwIfAborted(operation.signal);
        // Read this provider directly: Models.getModels intentionally hides per-provider failures.
        const catalog = normalizeModels(provider.getModels().map(mapModel));
        const custom = customSelections.get(operation.providerId);
        if (custom && !custom.custom.model.cost) for (const model of catalog) delete model.cost;
        return filterModelsByCapabilities(catalog, operation.requiredCapabilities);
      } catch (cause) {
        if (operation.signal?.aborted || (cause instanceof DOMException && cause.name === "AbortError")) throw abortError();
        throw safeAdapterError(cause, "catalog");
      }
    },

    getAuthStatus,
    resolveAuthStatus,
    refresh,

    async connect(request, connectOptions = {}) {
      throwIfAborted(connectOptions.signal);
      const controller = new AbortController();
      const signal = connectOptions.signal ? AbortSignal.any([connectOptions.signal, controller.signal]) : controller.signal;
      connectOptions = { ...connectOptions, signal };
      const secrets = request.authMethod === "api-key" ? [request.apiKey] : [];
      try {
        if (request.authMethod === "api-key" && !request.apiKey.trim()) {
          throw new AdapterError("auth", "API Key 不能为空");
        }

        if (request.connectionType === "custom") {
          registerCustom(customSelectionFromRequest(request));
          if (request.authMethod === "api-key") await saveApiKey(request.providerId, request.apiKey, signal);
        } else {
          const provider = options.models.getProvider(request.providerId);
          if (!provider) throw new AdapterError("catalog", "找不到指定的 provider");

          if (request.authMethod === "oauth") {
            if (!provider.auth.oauth?.login) {
              throw new AdapterError("capability", "该 provider 不支持 OAuth");
            }
            await withAbort(() => options.models.login(
              request.providerId, "oauth", interaction(connectOptions, secrets), options.loginOptions,
            ), signal);
          } else if (request.authMethod === "api-key") {
            if (!provider.auth.apiKey) {
              throw new AdapterError("capability", "该 provider 不支持 API Key");
            }
            if (provider.auth.apiKey.login) {
              let suppliedKey = false;
              await withAbort(() => options.models.login(
                request.providerId,
                "api_key",
                interaction({
                  ...connectOptions,
                  prompt: async (prompt) => {
                    throwIfAborted(signal);
                    throwIfAborted(prompt.signal);
                    if (prompt.type === "secret" && !suppliedKey) {
                      suppliedKey = true;
                      return request.apiKey;
                    }
                    if (!connectOptions.prompt) throw new AdapterError("capability", "此认证流程需要宿主提供 prompt handler");
                    return connectOptions.prompt(prompt);
                  },
                }, secrets),
                options.loginOptions,
              ), signal);
            } else {
              if (!apiKeyFallbackProviders.has(request.providerId)) {
                throw new AdapterError("capability", "该 provider 只能使用宿主环境凭证");
              }
              await saveApiKey(request.providerId, request.apiKey, signal);
            }
          } else if (!provider.auth.apiKey) {
            throw new AdapterError("capability", "该 provider 不支持宿主环境认证");
          }
        }

        throwIfAborted(signal);
        return { providerId: request.providerId, auth: await getAuthStatus(request.providerId, signal) };
      } catch (cause) {
        if (signal.aborted || (cause instanceof DOMException && cause.name === "AbortError")) throw abortError();
        throw safeAdapterError(cause, request.authMethod === "oauth" ? "oauth" : "auth");
      } finally {
        controller.abort();
        secrets.fill("");
        secrets.length = 0;
      }
    },

    async testConnection(selection, operation = {}) {
      throwIfAborted(operation.signal);
      let model: ReturnType<Models["getModel"]>;
      try {
        if (selection.connectionType === "custom") registerCustom(selection);
        model = options.models.getModel(selection.providerId, selection.modelId);
      } catch (cause) { throw safeAdapterError(cause, "catalog"); }
      if (!model) {
        return {
          state: "unreachable",
          message: "找不到指定的模型",
          testedAt: Date.now(),
          mayBeBillable: false,
        };
      }

      const controller = new AbortController();
      const abort = () => controller.abort();
      operation.signal?.addEventListener("abort", abort, { once: true });
      if (operation.signal?.aborted) controller.abort();
      const timer = setTimeout(abort, probeTimeoutMs);
      let dispatched = false;
      try {
        if (options.models.getAuth) {
          const resolved = await withAbort(() => options.models.getAuth!(model, { signal: controller.signal }), controller.signal);
          if (!resolved) return { state: "unreachable", message: "认证尚未配置", testedAt: Date.now(), mayBeBillable: false };
        }
        dispatched = true;
        const response = await withAbort(() => options.models.completeSimple(
          model,
          {
            messages: [
              { role: "user", content: probePrompt, timestamp: Date.now() },
            ],
          },
          { signal: controller.signal, maxTokens: 1, timeoutMs: probeTimeoutMs, maxRetries: 0 },
        ), controller.signal);
        if (operation.signal?.aborted) throw abortError();
        const reachable = !controller.signal.aborted && response.stopReason !== "error" && response.stopReason !== "aborted";
        return {
          state: reachable ? "reachable" : "unreachable",
          message: reachable
            ? "最小模型请求成功"
            : "最小模型请求失败或超时，请检查认证与网络",
          testedAt: Date.now(),
          mayBeBillable: true,
        };
      } catch (cause) {
        if (operation.signal?.aborted) throw abortError();
        return {
          state: "unreachable",
          message: controller.signal.aborted ? "最小模型请求超时" : safeAdapterError(cause, "network").message,
          testedAt: Date.now(),
          mayBeBillable: dispatched,
        };
      } finally {
        controller.abort();
        clearTimeout(timer);
        operation.signal?.removeEventListener("abort", abort);
      }
    },

    async disconnect(providerId, signal) {
      throwIfAborted(signal);
      try {
        await withAbort(() => options.models.logout(providerId, { signal }), signal);
        return await getAuthStatus(providerId, signal);
      } catch (cause) {
        if (signal?.aborted || (cause instanceof DOMException && cause.name === "AbortError")) throw abortError();
        throw safeAdapterError(cause, "auth");
      }
    },
  };
}
