import type { ModelSettingsText } from "./types";

export const zhCNText: ModelSettingsText = {
  eyebrow: "模型连接",
  title: "选择模型服务",
  description: "配置认证方式并选择要使用的模型。",
  methods: {
    subscription: "订阅登录",
    "api-key": "API Key",
    custom: "自定义接口",
  },
  providerLabel: "服务商",
  modelLabel: "模型",
  capabilityHint: "只显示满足所需输入能力的模型",
  apiKeyLabel: "API Key",
  baseUrlLabel: "Base URL",
  customModelLabel: "模型 ID",
  subscriptionTitle: "使用订阅账号登录",
  subscriptionDescription: "授权由适配器或宿主处理，组件不会接收 OAuth token。",
  connect: "连接",
  connecting: "连接中…",
  test: "测试连接",
  testing: "测试中…",
  save: "保存",
  saving: "保存中…",
  cancel: "取消",
  connected: "认证已配置",
  disconnected: "认证未配置",
  loading: "加载中…",
};

export const enUSText: ModelSettingsText = {
  eyebrow: "Model connection",
  title: "Choose a model service",
  description: "Configure authentication and select the model to use.",
  methods: { subscription: "Subscription", "api-key": "API key", custom: "Custom endpoint" },
  providerLabel: "Provider",
  modelLabel: "Model",
  capabilityHint: "Only models with the required input capabilities are shown",
  apiKeyLabel: "API key",
  baseUrlLabel: "Base URL",
  customModelLabel: "Model ID",
  subscriptionTitle: "Sign in with a subscription",
  subscriptionDescription: "The adapter or host handles authorization; OAuth tokens never enter the component.",
  connect: "Connect",
  connecting: "Connecting…",
  test: "Test connection",
  testing: "Testing…",
  save: "Save",
  saving: "Saving…",
  cancel: "Cancel",
  connected: "Authentication configured",
  disconnected: "Authentication not configured",
  loading: "Loading…",
};
