import type { ModelSettingsText } from "./types";

export const zhCNText: ModelSettingsText = {
  eyebrow: "模型连接",
  title: "选择模型服务",
  description: "配置认证方式并选择要使用的模型。",
  methods: {
    subscription: "订阅登录",
    "api-key": "API Key",
    custom: "自定义接口",
  },
  providerLabel: "服务商",
  modelLabel: "模型",
  capabilityHint: "只显示满足所需输入能力的模型",
  apiKeyLabel: "API Key",
  baseUrlLabel: "Base URL",
  customModelLabel: "模型 ID",
  subscriptionTitle: "使用订阅账号登录",
  subscriptionDescription: "授权由适配器或宿主处理，组件不会接收 OAuth token。",
  connect: "连接",
  connecting: "连接中…",
  disconnect: "断开认证",
  disconnecting: "断开中…",
  test: "测试连接",
  testing: "测试中…",
  save: "保存",
  saving: "保存中…",
  cancel: "取消",
  close: "关闭",
  authConfigured: "认证已配置",
  authUnconfigured: "认证未配置",
  authError: "认证状态异常",
  noProviders: "没有支持此认证方式的服务商",
  noModels: "没有满足条件的模型",
  retry: "重试",
  promptSubmit: "继续",
  operationTimeout: "认证操作超时，请重试",
  loading: "加载中…",
};

export const enUSText: ModelSettingsText = {
  eyebrow: "Model connection",
  title: "Choose a model service",
  description: "Configure authentication and select the model to use.",
  methods: { subscription: "Subscription", "api-key": "API key", custom: "Custom endpoint" },
  providerLabel: "Provider",
  modelLabel: "Model",
  capabilityHint: "Only models with the required input capabilities are shown",
  apiKeyLabel: "API key",
  baseUrlLabel: "Base URL",
  customModelLabel: "Model ID",
  subscriptionTitle: "Sign in with a subscription",
  subscriptionDescription: "The adapter or host handles authorization; OAuth tokens never enter the component.",
  connect: "Connect",
  connecting: "Connecting…",
  disconnect: "Disconnect",
  disconnecting: "Disconnecting…",
  test: "Test connection",
  testing: "Testing…",
  save: "Save",
  saving: "Saving…",
  cancel: "Cancel",
  close: "Close",
  authConfigured: "Authentication configured",
  authUnconfigured: "Authentication not configured",
  authError: "Authentication status error",
  noProviders: "No providers support this authentication method",
  noModels: "No models match the requirements",
  retry: "Retry",
  promptSubmit: "Continue",
  operationTimeout: "Authentication timed out; try again",
  loading: "Loading…",
};
