import type { ModelSettingsText } from "./types";

export const zhCNText: ModelSettingsText = {
  eyebrow: "模型连接",
  title: "选择模型服务",
  description: "配置认证方式并选择要使用的模型。",
  methods: {
    subscription: "订阅登录",
    "api-key": "API Key",
    custom: "自定义接口",
  },
  providerLabel: "服务商",
  modelLabel: "模型",
  capabilityHint: "只显示满足所需输入能力的模型",
  apiKeyLabel: "API Key",
  baseUrlLabel: "Base URL",
  customModelLabel: "模型 ID",
  displayNameLabel: "显示名称（可选）",
  protocolLabel: "协议",
  inputCapabilitiesLabel: "输入能力",
  textInputLabel: "文本",
  imageInputLabel: "图片",
  reasoningLabel: "推理模型（reasoning）",
  contextWindowLabel: "Context window",
  maxTokensLabel: "Max tokens",
  inputCostLabel: "输入价格（可选）",
  outputCostLabel: "输出价格（可选）",
  cacheReadCostLabel: "缓存读取价格（可选）",
  cacheWriteCostLabel: "缓存写入价格（可选）",
  priceUnitHint: "价格单位：每百万 token；输入和输出价格需同时填写。",
  priceUnknown: "价格未知（留空不代表免费）",
  corsHint: "浏览器直连需要服务端允许 CORS；后端代理须限制目标地址以防 SSRF。本地服务请填写实际 API 路径，如 /v1。",
  subscriptionTitle: "使用订阅账号登录",
  subscriptionDescription: "授权由适配器或宿主处理，组件不会接收 OAuth token。",
  connect: "连接",
  connecting: "连接中…",
  disconnect: "断开认证",
  disconnecting: "断开中…",
  test: "测试连接",
  testing: "测试中…",
  save: "保存",
  saving: "保存中…",
  cancel: "取消",
  close: "关闭",
  authConfigured: "认证已配置",
  authUnconfigured: "认证未配置",
  authError: "认证状态异常",
  noProviders: "没有支持此认证方式的服务商",
  noModels: "没有满足条件的模型",
  retry: "重试",
  promptSubmit: "继续",
  operationTimeout: "认证操作超时，请重试",
  loading: "加载中…",
};

export const enUSText: ModelSettingsText = {
  eyebrow: "Model connection",
  title: "Choose a model service",
  description: "Configure authentication and select the model to use.",
  methods: { subscription: "Subscription", "api-key": "API key", custom: "Custom endpoint" },
  providerLabel: "Provider",
  modelLabel: "Model",
  capabilityHint: "Only models with the required input capabilities are shown",
  apiKeyLabel: "API key",
  baseUrlLabel: "Base URL",
  customModelLabel: "Model ID",
  displayNameLabel: "Display name (optional)",
  protocolLabel: "Protocol",
  inputCapabilitiesLabel: "Input capabilities",
  textInputLabel: "Text",
  imageInputLabel: "Image",
  reasoningLabel: "Reasoning model",
  contextWindowLabel: "Context window",
  maxTokensLabel: "Max tokens",
  inputCostLabel: "Input cost (optional)",
  outputCostLabel: "Output cost (optional)",
  cacheReadCostLabel: "Cache read cost (optional)",
  cacheWriteCostLabel: "Cache write cost (optional)",
  priceUnitHint: "Cost per million tokens; enter both input and output prices.",
  priceUnknown: "Price unknown (blank does not mean free)",
  corsHint: "Browser requests require server-side CORS. Backend proxies must restrict destinations to prevent SSRF. Include the actual API path (e.g. /v1) for local servers.",
  subscriptionTitle: "Sign in with a subscription",
  subscriptionDescription: "The adapter or host handles authorization; OAuth tokens never enter the component.",
  connect: "Connect",
  connecting: "Connecting…",
  disconnect: "Disconnect",
  disconnecting: "Disconnecting…",
  test: "Test connection",
  testing: "Testing…",
  save: "Save",
  saving: "Saving…",
  cancel: "Cancel",
  close: "Close",
  authConfigured: "Authentication configured",
  authUnconfigured: "Authentication not configured",
  authError: "Authentication status error",
  noProviders: "No providers support this authentication method",
  noModels: "No models match the requirements",
  retry: "Retry",
  promptSubmit: "Continue",
  operationTimeout: "Authentication timed out; try again",
  loading: "Loading…",
};
